FROM php:8.3-cli-alpine

# Install system dependencies
RUN apk add --no-cache \
    unzip \
    libzip-dev \
    libprotobuf \
    protobuf \
    linux-headers \
    $PHPIZE_DEPS

# Install PHP extensions
RUN docker-php-ext-install zip pcntl sockets

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Copy application files
COPY . .

# Install dependencies including dev
RUN composer install

# Run tests
CMD ["./vendor/bin/pest"]
